### ISSUE TITLE
not really an issue but IntelliJ is misleading

### ISSUE THREAD

**Issue by meta8** [iravid/managedt#2]
when using 'traverse', intelliJ (2017.3 and latest stable scala plugin 2017.3.11.1) does not resolve type properly and indicates an error ("expression of type ManagedT[Task, Int] doesn't conform to expected type G_[B_]")
eg:
val resources: ManagedT[Task,List[Int]] = indices.traverse {
      (r: Int) => ManagedT(Task { println(s"Acquiring $r"); r})(r => Task(println(s"Cleaning $r")))
}

it bugged me for a while til I realized the issue was in intelliJ scala plugin, not in the code : types and compilation are OK ! Don't lose time on this ;-)

**Comment by iravid** [comment]
Yeah sorry about that, nothing I can do - Intellij fails to do the partial unification dance that scalac does.

Try ENSIME (https://ensime.org/) out :-)
